# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a275712543400b0684aa499c7ed4266f7bf8a2f54f835136e26704e6778b4ac7bbdc47a6b2ce1e586a26160128a6581bc2c8af2512f33f7da1f82b7341652ae

test:
  secret_key_base: 42a8d884d26da9978d9869a4f19e59473c5615e8d7048a12bb2300f3040fa17245a6c4f0fe531f62da2c054cd24bf78164113cf72021a6d6b99b934e70893cf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
